# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pizzeria/common_definitions.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'pizzeria/common_definitions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!pizzeria/common_definitions.proto\x12\x06\x66\x65\x65\x64me*;\n\x0eIngredientPrep\x12\x0b\n\x07NO_PREP\x10\x00\x12\x08\n\x04\x43HOP\x10\x01\x12\x08\n\x04\x44ICE\x10\x02\x12\x08\n\x04PEEL\x10\x03*5\n\rRecipeActions\x12\r\n\tNO_ACTION\x10\x00\x12\x08\n\x04\x42OIL\x10\x01\x12\x0b\n\x07\x43OMBINE\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pizzeria.common_definitions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INGREDIENTPREP']._serialized_start=45
  _globals['_INGREDIENTPREP']._serialized_end=104
  _globals['_RECIPEACTIONS']._serialized_start=106
  _globals['_RECIPEACTIONS']._serialized_end=159
# @@protoc_insertion_point(module_scope)
