# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pizzeria/recipe.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'pizzeria/recipe.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pizzeria import common_definitions_pb2 as pizzeria_dot_common__definitions__pb2
from pizzeria import ingredient_pb2 as pizzeria_dot_ingredient__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15pizzeria/recipe.proto\x12\x06\x66\x65\x65\x64me\x1a!pizzeria/common_definitions.proto\x1a\x19pizzeria/ingredient.proto\"}\n\x0bInstruction\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\'\n\x0bingredients\x18\x02 \x03(\x0b\x32\x12.feedme.Ingredient\x12%\n\x06\x61\x63tion\x18\x03 \x01(\x0e\x32\x15.feedme.RecipeActions\x12\x10\n\x08\x64uration\x18\x04 \x01(\x03\"\xb5\x01\n\x06Recipe\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\'\n\x0bingredients\x18\x02 \x03(\x0b\x32\x12.feedme.Ingredient\x12\x12\n\nshelf_life\x18\x03 \x01(\x05\x12\x10\n\x08servings\x18\x04 \x01(\x05\x12\x11\n\tbase_cost\x18\x05 \x01(\x02\x12\x0e\n\x06margin\x18\x06 \x01(\x02\x12\x18\n\x10preparation_time\x18\x07 \x01(\x03\x12\x11\n\tcook_time\x18\x08 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pizzeria.recipe_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INSTRUCTION']._serialized_start=95
  _globals['_INSTRUCTION']._serialized_end=220
  _globals['_RECIPE']._serialized_start=223
  _globals['_RECIPE']._serialized_end=404
# @@protoc_insertion_point(module_scope)
